services:
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.12.2-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  auction-svc:
    image: zhangweiwei1982/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres;User Id=postgres;Password=postgrespw;Database=auctions
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    depends_on:
      - postgres
      - rabbitmq

  search-svc:
    image: zhangweiwei1982/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - AuctionServiceUrl=http://auction-svc
    depends_on:
      - mongodb
      - rabbitmq
  
  identity-svc:
    image: zhangweiwei1982/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - IssuerUri=http://id.carsties.com
      - ClientApp=http://localhost:3000
      - ConnectionStrings__DefaultConnection=Server=postgres; User Id=postgres; Password=postgrespw; Database=identity
    ports:
      - 80:80
    depends_on:
      - postgres

  gateway-svc:
    image: zhangweiwei1982/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=http://web-app
    ports:
      - 6001:80

  bid-svc:
    image: zhangweiwei1982/bid-svc:latest
    build:
      context: .
      dockerfile: src/BiddingService/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuction=http://auction-svc:7777
    depends_on:
      - mongodb
      - rabbitmq

  notify-svc:
    image: zhangweiwei1982/notify-svc:latest
    build:
      context: .
      dockerfile: src/NotificationService/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    depends_on:
      - rabbitmq

  web-app:
    image: zhangweiwei1982/web-app
    build:
      context: .
      dockerfile: frontend/web-app/dockerfile
    volumes:
      - /var/lib/web/data
    extra_hosts:
      - id.carsties.com:172.23.0.8
    environment:
      - AUTH_SECRET="say_lalisa_love_me_lalisa_love_me_hey"
      - AUTH_URL=http://localhost:3000
      - AUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gateway-svc/
      - ID_URL=http://id.carsties.com
      - ID_URL_INTERNAL=http://identity-svc
      - NOTIFY_URL=http://gateway-svc/notifications

    ports:
      - 3000:3000

volumes:
  postgres_data:
  mongo_data:
