apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-svc
spec:
  selector:
    matchLabels:
      app: bid-svc
  template:
    metadata:
      labels:
        app: bid-svc
    spec:
      containers:
      - name: bid-svc
        image: zhangweiwei1982/bid-svc:latest
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: bid-svc-config
---
apiVersion: v1
kind: Service
metadata:
  name: bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: bid-svc
  ports:
  - port: 80
    targetPort: 80
    name: web