apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
spec:
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
      - name: gateway-svc
        image: zhangweiwei1982/gateway-svc:latest
        env:
          - name: ClientApp
            value: https://app.carsties.com
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-clusterip
spec:
  type: ClusterIP
  selector:
    app: gateway-svc
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-node
spec:
  type: NodePort
  selector:
    app: gateway-svc
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002