apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: zhangweiwei1982/web-app
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: webapp-svc-config
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - port: 3000
    targetPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: webapp-lb
# spec:
#   type: NodePort
#   selector:
#     app: webapp
#   ports:
#   - port: 80
#     targetPort: 3000
#     nodePort: 30001
