apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: zhangweiwei1982/web-app
        env:
          - name: AUTH_SECRET
            value: say_lalisa_love_me_lalisa_love_me_hey
          - name: AUTH_URL
            value: https://app.carsties.com
          - name: API_URL
            value: http://gateway-svc/
          - name: ID_URL
            value: https://id.carsties.com
          - name: NOTIFY_URL
            value: https://api.carsties.com/notifications
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-lb
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30001
