apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapptest
spec:
  selector:
    matchLabels:
      app: webapptest
  template:
    metadata:
      labels:
        app: webapptest
    spec:
      containers:
      - name: webapptest
        image: zhangweiwei1982/web-app-test:latest
        env:
          - name: NEXT_PUBLIC_API_URL
            value: http://gateway-clusterip
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapptest-clusterip
spec:
  type: ClusterIP
  selector:
    app: webapptest
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapptest-lb
spec:
  type: NodePort
  selector:
    app: webapptest
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30077
